#!/bin/bash
##################################################
#
#           ** DO NOT EDIT THIS FILE **
#
##################################################
# Version: 2022-12-30
for keyval in  $(grep -E '": [^\{]' ./app/config/base.json | sed -e 's/: /=/' -e "s/\(\,\)$//"); do
    echo 'export ' $keyval && eval export $keyval
    echo $keyval | sed 's/"//g' >> ./docker.env
done;

docker ps -a | grep $dockerBaseName/$name | awk '{ system("docker container logs " $1) }'
